TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

PROD_IOC += testOpenClose
testOpenClose_SRCS += testOpenClose.cpp
PROD_LIBS += VimbaCPP
PROD_SYS_LIBS += VimbaC

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

